//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutions.OnlineSelling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCalendarGallery
    {
        public int GalleryId { get; set; }
        public int EventId { get; set; }
        public string ImagePath { get; set; }
        public string ImageTitle { get; set; }
        public string ImageDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual TblCalendar TblCalendar { get; set; }
    }
}
