//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutions.OnlineSelling.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductCategoryMapping
    {
        public int ProductCategoryId { get; set; }
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
